{% set name = "fenicsx-ldrb" %}
{% set python_min = "3.10" %}
{% set version = "0.1.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fenicsx_ldrb-{{ version }}.tar.gz
  sha256: 16c9c5c815d12b3cf1dcac8537e5963d5523cf0b3808dc031ca6a3b116a7967a

build:
  number: 0
  noarch: python
  entry_points:
    - "ldrb=ldrb.cli:main"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - adios4dolfinx
    - numba
    - fenics-dolfinx

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pip
    - scifem
    - cardiac-geometriesx
  imports:
    - ldrb
  source_files:
    - tests/
    - pyproject.toml
  commands:
    - ldrb --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests


about:
  home: https://github.com/finsberg/fenicsx-ldrb
  summary: Laplace-Dirichlet Rule-based algorithm for assigning myocardial fiber orientations
  license: MIT
  license_file: LICENSE
  doc_url: https://finsberg.github.io/fenicsx-ldrb/
  dev_url: https://github.com/finsberg/fenicsx-ldrb

extra:
  recipe-maintainers:
    - finsberg
